### ISSUE TITLE
species lacking from unified

### ISSUE THREAD

**Issue by timadriaens** [trias-project/unified-checklist#36]
I accidentally noticed Crassula helmsii does not occur on the unified. It is one of our most notorious invasive plant species. I see the accepted (that also occurs in the other GRIIS checklists) is [this one](https://www.gbif.org/species/8035075), however, when mapping rinse and manual of alien plants is was mapped on [the synonym ](https://www.gbif.org/species/5362054). 

@peterdesmet @damianooldoni  can you check what went wrong here?

**Comment by peterdesmet** [comment]
Everything is as expected: the taxa in the source checklist are written as:

Crassula helmsii (Kirk) Cockayne
Crassula helmsii (T. Kirk) Cock.

And considered synonyms of Crassula helmsii A.Berger. As a result they are listed in the verification spreadsheet, but were not verified. I have now done this.

**Comment by peterdesmet** [comment]
Fixed in 0fe234d92acefc144c223ec93dd59cf8b23687f7

**Comment by timadriaens** [comment]
@peterdesmet @damianooldoni  apparently not fixed yet as not yet in unified I downloaded on 19/06/2019

**Comment by damianooldoni** [comment]
I find a taxon `Crassula helmsii A.Berger` online:
https://www.gbif.org/species/156873457
It has been added as accepted taxon in verification file (taxonKey 146042246)
@timadriaens : Can you check it again?

**Comment by qgroom** [comment]
Crassula helmsii (Kirk) Cockayne seems to be the correct name for this species. The backbone is wrong in this case Crassula helmsii A.Berger is a synonym of Crassula helmsii (Kirk) Cockayne, not the other way around. Actually, it should be Crassula helmsii (Kirk) A.Berger.

**Comment by timadriaens** [comment]
I can see that _Crassula helmsii_ A.Berger is there now.

**Comment by timadriaens** [comment]
@LienReyserhove We need to add the alien bird checklist (even if it has little species) because some Union List species that occur in Belgium (e.g. Threskiornis aethiopicus, Acridotheres tristis) are lacking now. Also cannot find _Humulus scandens_ (_Humulus japonicus_) on the unified whereas it was observed in 1954 but perhaps this was only very revently added to MAP?
